/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wikim' at '15. 4. 6 오후 10:09' with Gradle 2.2.1
 *
 * @author wikim, @date 15. 4. 6 오후 10:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
